jobs:
  build:
    machine: true
    steps:
      - checkout
      # build
      - run: make all
      # export root
      - store_artifacts:
          path: RHWSL.zip
      - save_cache:
          key: rhwsl-zip
          paths:
            -  RHWSL.zip
      # cleanup
      - run: make clean
  deploy:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - restore_cache:
          keys:
            - rhwsl-zip
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} RHWSL.zip
workflows:
  version: 2
  untagged-build:
    jobs:
      - build
  tagged-build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
